public with sharing class B2BConstants {

  public static final String HTTP_POST = 'POST';
  public static final String HTTP_HEADER_CONTENT_TYPE = 'Content-Type';
  public static final String HTTP_HEADER_CONTENT_TYPE_JSON = 'application/json';
  public static final String CALLOUT = 'callout:';
  public static final String HTTP_HEADER_DATE = 'Date';
  public static final String HTTP_HEADER_AUTHORIZATION = 'Authorization';
  public static final String HTTP_HEADER_HMAC_ALGORITHM = 'x-hmac-hash-algorithm';
  public static final String HTTP_HEADER_CONTENT_TYPE_ENCODED = 'application/x-www-form-urlencoded';
}