public with sharing class StaticVariables 
{
    public static Boolean beforeInsertUpdateCase = true;
    public static Boolean afterInsertCase = true;
    public static Boolean AfterTgrEventsCase = TRUE;
    
    public static final string EVENT_AFTER_INSERT = 'Insert';
    public static final string EVENT_AFTER_UPDATE = 'Update';
    public static final string EVENT_AFTER_DELETE = 'Delete';
    public static final string EVENT_AFTER_UNDELETE = 'Undelete';
    
    public static final string SOBJECT_CASE = 'Case';
    public static final string SOBJECT_ACCOUNT = 'Account';
    
    public static final string TECHNICAL_AND_FIELD_SERVICES = 'Technical & Field Services';
}