@isTest
public class Test_BatchDuplAccounts_IgnoreDuplicate
{
/*
    static testmethod void testBatchDuplAccounts() 
    {
        //DSE__DS_Duplicates__c da = new DSE__DS_Duplicates__c();
        //insert da;
        
        BatchDuplAccounts_IgnoreDuplSetToTrue btc1=new BatchDuplAccounts_IgnoreDuplSetToTrue();
        database.executebatch(btc1,2000);
        
        BatchDuplAccounts_IgnoreDuplSetToFalse btc2=new BatchDuplAccounts_IgnoreDuplSetToFalse();
        database.executebatch(btc2,2000);
        
    }
*/    
}