@isTest
public class TestSchedulerBatchertoUpdateDup {
    /*public static DSE__DS_DuplicateBean__c record1;
    public static DSE__DS_DuplicateBean__c record2;
    public static DSE__DS_DuplicateBean__c record3;
    public static DSE__DS_DuplicateBean__c record4;
    public static DSE__DS_DuplicateBean__c record5;
    static
        {
            record1 = new DSE__DS_DuplicateBean__c();
            record2 = new DSE__DS_DuplicateBean__c();
            record3 = new DSE__DS_DuplicateBean__c();
            record4 = new DSE__DS_DuplicateBean__c();
            record5 = new DSE__DS_DuplicateBean__c();
            
            insert new List<DSE__DS_DuplicateBean__c>{record1,record2,record3,record4,record5};
            
        }
    
    static testmethod void testMethod1()
    {
        Test.startTest();
        ScheduleBatchertoUpdateDup schedulable = new ScheduleBatchertoUpdateDup();
        String sch = '0  00 1 3 * ?';
        system.schedule('Test', sch, schedulable);
        Test.stopTest();
    }*/
}